workflows:
  android-workflow:
    name: Android Build

    environment:
      java: 17

    scripts:
      - name: Give permission
        script: chmod +x gradlew

      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
